Refactorized pb-flow with getopts

diff --git a/scripts/pb-flow b/scripts/pb-flow
--- a/scripts/pb-flow
+++ b/scripts/pb-flow
@@ -31,8 +31,29 @@ if [ ! -d "${POLYBENCH_DIR}" ]; then
   echo "Please pass in a valid polybench directory as #1 arg."
   exit 1
 fi
+shift # Remove POLYBENCH_DIR from the argument list.
 
-ENABLE_POLYMER="${2:-0}"
+# Variables to set.
+ENABLE_POLYMER="0"
+ENABLE_COSIM="0"
+DEBUG="0"
+
+while getopts ":dpc" opt; do 
+  case ${opt} in
+    d)
+      DEBUG="1"
+      ;;
+    p)
+      ENABLE_POLYMER="1"
+      ;;
+    c)
+      ENABLE_COSIM="1"
+      ;;
+    \?)
+      echo "Usage: pb-flow [-p USE POLYMER] [-c COSIM] [-d DEBUG]"
+      ;;
+  esac
+done
 
 # ---------------------- FUNCTIONS ------------------------------
 
@@ -158,20 +179,25 @@ EOF
   echo "${dst_file}"
 }
 
-# Generate the run_hls.tcl file
-function gen_vitis_tcl() {
+# Generate run_hls.tcl that passes Phism generated LLVM-IR to Vitis.
+# Returns the full file path of run_hls.tcl
+function gen_vitis_phism_tcl() {
   local src_file="${1}"
   local src_base
   local src_dir
   local dst_file
   local top_func
   local dummy_c_src
+  local config="config_bind -effort high"
+
+  # Disable high effort in debug mode.
+  if [[ ${DEBUG} -eq 1 ]]; then
+    config=""
+  fi
 
   src_dir="$(dirname "${src_file}")"
   src_base="$(basename "${src_dir}")"
   dst_file="$(dirname "${src_file}")/run_hls.tcl"
-  dst_tb_file="$(dirname "${src_file}")/tb_gen.tcl"
-  dst_cosim_file="$(dirname "${src_file}")/cosim.tcl"
   top_func="$(get_top_func "${src_file}")"
   dummy_c_src="$(gen_dummy_c "${src_file}")"
 
@@ -179,9 +205,6 @@ function gen_vitis_tcl() {
   if [[ ${ENABLE_POLYMER} -eq 1 ]]; then
     top_func="${top_func}_opt"
   fi
-
-  # Remove 'static' in all functions - the top design cannot be static
-  sed -i 's/static//g' ${src_dir}/${src_base}.c
 
   # Synthesis script
   cat <<EOF > "${dst_file}"
@@ -192,7 +215,7 @@ set_top ${top_func}
 open_solution -reset solution1
 set_part "zynq"
 create_clock -period "100MHz"
-config_bind -effort high
+${config}
 
 set ::LLVM_CUSTOM_CMD {\$LLVM_CUSTOM_OPT -no-warn ${src_file} -o \$LLVM_CUSTOM_OUTPUT}
 
@@ -201,18 +224,44 @@ csynth_design
 exit
 EOF
 
+  echo "${dst_file}"
+}
+
+# Generate tb_gen.tcl that generates the test bench.
+# Returns the full file path of tb_gen.tcl
+function gen_vitis_tbgen_tcl() {
+  local src_file="${1}"
+  local src_base
+  local src_dir
+  local dst_file
+  local top_func
+  local config="config_bind -effort high"
+
+  src_dir="$(dirname "${src_file}")"
+  src_base="$(basename "${src_dir}")"
+  dst_file="$(dirname "${src_file}")/tb_gen.tcl"
+  top_func="$(get_top_func "${src_file}")"
+
+  # Disable high effort in debug mode.
+  if [[ ${DEBUG} -eq 1 ]]; then
+    config=""
+  fi
+
+  # Remove 'static' in all functions - the top design cannot be static
+  sed -i 's/static//g' "${src_dir}/${src_base}.c"
+
   # Testbench generation script / C baseline
   # TODO: need to handle these lib and polybench.c properly
-  cat <<EOF > "${dst_tb_file}"
+  cat <<EOF > "${dst_file}"
 open_project -reset tb
-add_files {${src_dir}/${src_base}.c} -cflags "-I ${src_dir} -I /workspace/example/polybench/utilities -DMINI_DATASET" -csimflags "-I ${src_dir} -I /workspace/example/polybench/utilities -DMINI_DATASET"
-add_files -tb {${src_dir}/${src_base}.c /workspace/example/polybench/utilities/polybench.c} -cflags "-I ${src_dir} -I /workspace/example/polybench/utilities -DMINI_DATASET" -csimflags "-I ${src_dir} -I /workspace/example/polybench/utilities -DMINI_DATASET"
+add_files {${src_dir}/${src_base}.c} -cflags "-I ${src_dir} -I ${src_dir}/../utilities -DMINI_DATASET" -csimflags "-I ${src_dir} -I ${src_dir}/../utilities -DMINI_DATASET"
+add_files -tb {${src_dir}/${src_base}.c ${src_dir}/../utilities/polybench.c} -cflags "-I ${src_dir} -I ${src_dir}/../utilities -DMINI_DATASET" -csimflags "-I ${src_dir} -I ${src_dir}/../utilities -DMINI_DATASET"
 set_top ${top_func}
 
 open_solution -reset solution1
 set_part "zynq"
 create_clock -period "100MHz"
-config_bind -effort high
+${config}
 
 csim_design
 csynth_design
@@ -221,8 +270,22 @@ cosim_design
 exit
 EOF
 
-  # Co-simulation script
-  cat <<EOF > "${dst_cosim_file}"
+  echo "${dst_file}"
+}
+
+# Generate cosim.tcl file that generates the test bench.
+# Returns the full file path of cosim.tcl
+function gen_vitis_cosim_tcl() {
+  local src_file="${1}"
+  local src_base
+  local src_dir
+  local dst_file
+
+  src_dir="$(dirname "${src_file}")"
+  src_base="$(basename "${src_dir}")"
+  dst_file="$(dirname "${src_file}")/cosim.tcl"
+
+  cat <<EOF > "${dst_file}"
 open_project tb
 
 open_solution solution1
@@ -232,46 +295,56 @@ cosim_design
 exit
 EOF
 
-  echo "${src_file}"
+  echo "${dst_file}"
 }
 
 # Run Vitis.
 function run_vitis() {
   local src_file="${1}"
-  local dst_file="$(dirname "${src_file}")/run_hls.tcl"
-  local dst_tb_file="$(dirname "${src_file}")/tb_gen.tcl"
-  local dst_cosim_file="$(dirname "${src_file}")/cosim.tcl"
+  local phism_tcl_file
   local src_dir
   
   src_dir="$(dirname "${src_file}")"
+  phism_tcl_file="$(gen_vitis_phism_tcl "${src_file}")"
 
   cd "${src_dir}"
 
-  set -x
-
   # Synthesize for Phism
-  vitis_hls "${dst_file}" &> "${src_dir}"/vhls.syn.log
+  vitis_hls "${phism_tcl_file}" &> "${src_dir}"/vhls.syn.log
 
   # Generate test bench
-  vitis_hls "${dst_tb_file}" &> "${src_dir}"/vhls.tbgen.log
-  if grep -q "*** C/RTL co-simulation finished: FAIL ***" "${src_dir}"/vhls.tbgen.log; then
-    echo "*** C/RTL co-simulation finished: C BASELINE - FAIL ***"
-  elif ! grep -q "*** C/RTL co-simulation finished: PASS ***" "${src_dir}"/vhls.tbgen.log; then
-    echo "*** C/RTL co-simulation failed: C BASELINE - UNKNOWN ERROR ***"
-  fi
+  if [[ ${ENABLE_COSIM} -eq 1 ]]; then
+    local tbgen_tcl_file
+    local cosim_tcl_file
 
-  # Copy the kernel from Phism to the test bench
-  cp "${src_dir}"/proj/solution1/syn/verilog/*.v* "${src_dir}"/tb/solution1/sim/verilog/
-  
-  # Run co-simulation
-  vitis_hls "${dst_cosim_file}" &> "${src_dir}"/vhls.cosim.log
-  if grep -q "*** C/RTL co-simulation finished: PHISM - FAIL ***" "${src_dir}"/vhls.cosim.log; then
-    echo "*** C/RTL co-simulation finished: FAIL ***"
-  elif ! grep -q "*** C/RTL co-simulation finished: PASS ***" "${src_dir}"/vhls.cosim.log; then
-    echo "*** C/RTL co-simulation failed: PHISM - UNKNOWN ERROR ***"
-  fi
+    tbgen_tcl_file="$(gen_vitis_tbgen_tcl "${src_file}")"
+    cosim_tcl_file="$(gen_vitis_cosim_tcl "${src_file}")"
 
-  set +x
+    vitis_hls "${tbgen_tcl_file}" &> "${src_dir}"/vhls.tbgen.log
+    if grep -q "C/RTL co-simulation finished: FAIL" "${src_dir}"/vhls.tbgen.log; then
+      echo "*** C/RTL co-simulation finished: C BASELINE - FAIL ***"
+    elif ! grep -q "C/RTL co-simulation finished: PASS" "${src_dir}"/vhls.tbgen.log; then
+      echo "*** C/RTL co-simulation failed: C BASELINE - UNKNOWN ERROR ***"
+    fi
+
+    if [ ! -d "${src_dir}"/tb/solution1/sim/verilog/ ]; then
+      echo "tbgen failed to create the target directory: "
+      echo "  ${src_dir}/tb/solution1/sim/verilog/"
+      exit 1
+    fi
+
+    # Copy the kernel from Phism to the test bench
+    cp "${src_dir}"/proj/solution1/syn/verilog/*.v* "${src_dir}"/tb/solution1/sim/verilog/
+    
+    # Run co-simulation
+    vitis_hls "${cosim_tcl_file}" &> "${src_dir}"/vhls.cosim.log
+    if grep -q "C/RTL co-simulation finished: FAIL" "${src_dir}"/vhls.cosim.log; then
+      echo "*** C/RTL co-simulation finished: PHISM - FAIL ***"
+    elif ! grep -q "C/RTL co-simulation finished: PASS" "${src_dir}"/vhls.cosim.log; then
+      echo "*** C/RTL co-simulation failed: PHISM - UNKNOWN ERROR ***"
+    fi
+
+  fi
 
   # Read time from vitis_hls.log
   # e.g. $finish called at time : 13920290 ps
@@ -298,10 +371,9 @@ function eval_file() {
   poly_src_file="$(polymer_opt "${kern_src_file}")"
   llvm_src_file="$(lower_mlir_to_llvm "${poly_src_file}")"
   vitis_src_file="$(opt_llvm_for_vitis "${llvm_src_file}")"
-  vitis_tcl_file="$(gen_vitis_tcl "${vitis_src_file}")"
 
   local status
-  status="$(run_vitis "${vitis_tcl_file}")"
+  status="$(run_vitis "${vitis_src_file}")"
 
   if [[ "${status}" = "0" ]]; then
     echo " SUCCESS"
