Added script for co-simulations - results unverified

diff --git a/scripts/pb-flow b/scripts/pb-flow
--- a/scripts/pb-flow
+++ b/scripts/pb-flow
@@ -5,6 +5,7 @@
 # Usage:
 #   ./pb-flow <polybench directory>
 
+set -x
 set -o errexit
 set -o pipefail
 set -o nounset
@@ -51,6 +52,7 @@ function compile_c_to_mlir() {
 
   mlir-clang "${src_file}" \
     -memref-fullrank \
+    -D MINI_DATASET \
     -I="${LLVM_LIBDIR}/clang/13.0.0/include" \
     -I="${POLYBENCH_DIR}/utilities" > "${dst_file}"
 
@@ -159,12 +161,16 @@ EOF
 function gen_vitis_tcl() {
   local src_file="${1}"
   local src_base
+  local src_dir
   local dst_file
   local top_func
   local dummy_c_src
 
-  src_base="$(basename "$(dirname "${src_file}")")"
+  src_dir="$(dirname "${src_file}")"
+  src_base="$(basename "${src_dir}")"
   dst_file="$(dirname "${src_file}")/run_hls.tcl"
+  dst_tb_file="$(dirname "${src_file}")/tb_gen.tcl"
+  dst_cosim_file="$(dirname "${src_file}")/cosim.tcl"
   top_func="$(get_top_func "${src_file}")"
   dummy_c_src="$(gen_dummy_c "${src_file}")"
 
@@ -172,6 +178,9 @@ function gen_vitis_tcl() {
   if [[ ${ENABLE_POLYMER} -eq 1 ]]; then
     top_func="${top_func}_opt"
   fi
+
+  # Remove 'static' in all functions - the top design cannot be static
+  sed -i 's/static//g' ${src_dir}/${src_base}.c
 
   # Synthesis script
   cat <<EOF > "${dst_file}"
@@ -182,24 +191,21 @@ set_top ${top_func}
 open_solution -reset solution1
 set_part "zynq"
 create_clock -period "100MHz"
-
-set ::LLVM_CUSTOM_CMD {\$LLVM_CUSTOM_OPT -mem2reg ${src_file} -o \$LLVM_CUSTOM_OUTPUT}
-
 config_bind -effort high
+
+set ::LLVM_CUSTOM_CMD {\$LLVM_CUSTOM_OPT -no-warn ${src_file} -o \$LLVM_CUSTOM_OUTPUT}
+
 csynth_design
 
 exit
 EOF
 
-  echo "${dst_file}"
-
   # Testbench generation script / C baseline
-  # TODO: add another file name
-  cat <<EOF > "${dst_file}"
+  # TODO: need to handle these lib and polybench.c properly
+  cat <<EOF > "${dst_tb_file}"
 open_project -reset tb
-# TODO: change to  C files
-# add_files ../dct_src/dct.cpp
-# add_files -tb ../dct_src/out.golden.dat -cflags "-Wno-unknown-pragmas" -csimflags "-Wno-unknown-pragmas"
+add_files {${src_dir}/${src_base}.c} -cflags "-I ${src_dir} -I /workspace/example/polybench/utilities -DMINI_DATASET" -csimflags "-I ${src_dir} -I /workspace/example/polybench/utilities -DMINI_DATASET"
+add_files -tb {${src_dir}/${src_base}.c /workspace/example/polybench/utilities/polybench.c} -cflags "-I ${src_dir} -I /workspace/example/polybench/utilities -DMINI_DATASET" -csimflags "-I ${src_dir} -I /workspace/example/polybench/utilities -DMINI_DATASET"
 set_top ${top_func}
 
 open_solution -reset solution1
@@ -214,46 +220,49 @@ cosim_design
 exit
 EOF
 
-  echo "${dst_file}"
-
   # Co-simulation script
-  # TODO: add another file name
-  cat <<EOF > "${dst_file}"
+  cat <<EOF > "${dst_cosim_file}"
 open_project tb
 
-open_solution -reset solution1
+open_solution solution1
 
 cosim_design
 
 exit
 EOF
 
-  echo "${dst_file}"
+  echo "${src_file}"
 }
 
 # Run Vitis.
 function run_vitis() {
   local src_file="${1}"
+  local dst_file="$(dirname "${src_file}")/run_hls.tcl"
+  local dst_tb_file="$(dirname "${src_file}")/tb_gen.tcl"
+  local dst_cosim_file="$(dirname "${src_file}")/cosim.tcl"
   local src_dir
   
   src_dir="$(dirname "${src_file}")"
 
   cd "${src_dir}"
-  vitis_hls "${src_file}" &>/dev/null
+  # Synthesize for Phism
+  vitis_hls "${dst_file}" &> "${src_dir}"/vhls.syn.log
 
   # Generate test bench
-  # TODO: Make sure files are correct...
-  vitis_hls "${src_file}" &>/dev/null
-  cp proj/solution1/sim/verilog/*.v* tb/solution1/sim/verilog/
+  vitis_hls "${dst_tb_file}" &> "${src_dir}"/vhls.tbgen.log
+  
+  # Copy the kernel from Phism to the test bench
+  cp "${src_dir}"/proj/solution1/syn/verilog/*.v* "${src_dir}"/tb/solution1/sim/verilog/
   
   # Run co-simulation
-  vitis_hls "${src_file}" &>/dev/null
-  # if "*** C/RTL co-simulation finished: FAIL ***" in vitis_hls.log then
-  # report error
-  # else if "*** C/RTL co-simulation finished: PASS ***" in vitis_hls.log then
-  # success
-  # else
-  # something went wrong...
+  vitis_hls "${dst_cosim_file}" &> "${src_dir}"/vhls.cosim.log
+  if grep -q "*** C/RTL co-simulation finished: FAIL ***" "${src_dir}"/vhls.cosim.log; then
+    echo "*** C/RTL co-simulation finished: FAIL ***"
+    exit 1
+  elif ! grep -q "*** C/RTL co-simulation finished: FAIL ***" "${src_dir}"/vhls.cosim.log; then
+    echo "*** C/RTL co-simulation failed: UNKNOWN ERROR ***"
+    exit 1
+  fi
 
   # Read time from vitis_hls.log
   # e.g. $finish called at time : 13920290 ps
