Co-simulation in pb-flow (#7)
* Added initial Dockerfile for Phism

* Added test command for polybench

* Added docker instructions to README.md

* Added required package for Vitis HLS

* Format

* Added initial template for cosim script in pb-flow

* Added script for co-simulations - results unverified

* Updated cosim script

* Updated docs and scripts

* Updated CI script to use the latest build script

* Self host workflow (#6)

* Try out self-hosted workflow

* Reverted libclang prefix configure

* Try out self-hosted workflow

* Reverted libclang prefix configure

* Improved the README a bit

* Ignore debug directories

* Added docker instructions to README.md

* New DOCKER doc

* Refactorized pb-flow with getopts

* Added LD_LIBRARY_PATH into Dockerfile

* Updated Makefile with the latest pb-flow options

* Fixed path error for utilities

* Renamed GitHub workflow

* Updated docs and scripts

* Add synth & cosim to CI

Signed-off-by: Vincent Zhao <vincentzhaorz@gmail.com>

* Fixed llvm hash problem

* Fixed a typo in path

* Ask to build locally instead of /tmp

* README updated, removed cosim in CI

* Removed workflow MD5 from LLVM cache

* Add constant propagation to fix loop bounds

* Added Ninja detection and fixed CC/CXX issue

* Fixed various Polygeist issues

diff --git a/scripts/pb-flow b/scripts/pb-flow
--- a/scripts/pb-flow
+++ b/scripts/pb-flow
@@ -11,7 +11,9 @@ set -o nounset
 
 # ---------------------- GLOBALS --------------------------------
 TIMESTAMP="$(date "+%Y%m%d-%H%M%S")"
+
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
+WORKDIR="${DIR}/../tmp/phism/pb-flow.${TIMESTAMP}"
 LLVM_DIR="${DIR}/../llvm"
 LLVM_BINDIR="${LLVM_DIR}/build/bin"
 LLVM_LIBDIR="${LLVM_DIR}/build/lib"
@@ -31,8 +33,29 @@ if [ ! -d "${POLYBENCH_DIR}" ]; then
   echo "Please pass in a valid polybench directory as #1 arg."
   exit 1
 fi
+shift # Remove POLYBENCH_DIR from the argument list.
 
-ENABLE_POLYMER="${2:-0}"
+# Variables to set.
+ENABLE_POLYMER="0"
+ENABLE_COSIM="0"
+DEBUG="0"
+
+while getopts ":dpc" opt; do 
+  case ${opt} in
+    d)
+      DEBUG="1"
+      ;;
+    p)
+      ENABLE_POLYMER="1"
+      ;;
+    c)
+      ENABLE_COSIM="1"
+      ;;
+    \?)
+      echo "Usage: pb-flow [-p USE POLYMER] [-c COSIM] [-d DEBUG]"
+      ;;
+  esac
+done
 
 # ---------------------- FUNCTIONS ------------------------------
 
@@ -53,9 +76,22 @@ function compile_c_to_mlir() {
 
   mlir-clang "${src_file}" \
     -memref-fullrank \
+    -D MINI_DATASET \
     -I="${LLVM_LIBDIR}/clang/13.0.0/include" \
     -I="${POLYBENCH_DIR}/utilities" > "${dst_file}"
 
+  echo "${dst_file}"
+}
+
+# Do some preprocessing before extracting top function.
+function preprocess_mlir() {
+  local src_file="${1}"
+  local dst_file="${src_file%.mlir}.pre.mlir"
+
+  mlir-opt "${src_file}" \
+    -sccp \
+    -canonicalize > "${dst_file}"
+  
   echo "${dst_file}"
 }
 
@@ -83,7 +119,7 @@ function polymer_opt() {
       -insert-redundant-load \
       -extract-scop-stmt \
       -pluto-opt \
-      -inline 2>/dev/null > "${dst_file}"
+      2>"${dst_file%.mlir}.log" > "${dst_file}"
   else
     cp "${src_file}" "${dst_file}"
   fi
@@ -113,11 +149,6 @@ function opt_llvm_for_vitis() {
   local top_func
   top_func="$(get_top_func "${src_file}")"
 
-  # Polymer optimized functions have an _opt suffix.
-  if [[ ${ENABLE_POLYMER} -eq 1 ]]; then
-    top_func="${top_func}_opt"
-  fi
-
   "${LLVM_BINDIR}/opt" "${src_file}" \
     -S \
     -enable-new-pm=0 \
@@ -145,11 +176,6 @@ function gen_dummy_c() {
   dst_file="$(dirname "${src_file}")/${src_base}.dummy.c"
   top_func="$(get_top_func "${src_file}")"
 
-  # Polymer optimized functions have an _opt suffix.
-  if [[ ${ENABLE_POLYMER} -eq 1 ]]; then
-    top_func="${top_func}_opt"
-  fi
-
 cat <<EOF > "${dst_file}"
 void ${top_func}() {}
 EOF
@@ -157,36 +183,115 @@ EOF
   echo "${dst_file}"
 }
 
-# Generate the run_hls.tcl file
-function gen_vitis_tcl() {
+# Generate run_hls.tcl that passes Phism generated LLVM-IR to Vitis.
+# Returns the full file path of run_hls.tcl
+function gen_vitis_phism_tcl() {
   local src_file="${1}"
   local src_base
+  local src_dir
   local dst_file
   local top_func
   local dummy_c_src
+  local config="config_bind -effort high"
 
-  src_base="$(basename "$(dirname "${src_file}")")"
+  # Disable high effort in debug mode.
+  if [[ ${DEBUG} -eq 1 ]]; then
+    config=""
+  fi
+
+  src_dir="$(dirname "${src_file}")"
+  src_base="$(basename "${src_dir}")"
   dst_file="$(dirname "${src_file}")/run_hls.tcl"
   top_func="$(get_top_func "${src_file}")"
   dummy_c_src="$(gen_dummy_c "${src_file}")"
 
-  # Polymer optimized functions have an _opt suffix.
-  if [[ ${ENABLE_POLYMER} -eq 1 ]]; then
-    top_func="${top_func}_opt"
-  fi
-
-cat <<EOF > "${dst_file}"
+  # Synthesis script
+  cat <<EOF > "${dst_file}"
 open_project -reset proj
 add_files ${dummy_c_src}
 set_top ${top_func}
 
 open_solution -reset solution1
 set_part "zynq"
-create_clock -period "75MHz"
+create_clock -period "100MHz"
+${config}
 
-set ::LLVM_CUSTOM_CMD {\$LLVM_CUSTOM_OPT -mem2reg ${src_file} -o \$LLVM_CUSTOM_OUTPUT}
+set ::LLVM_CUSTOM_CMD {\$LLVM_CUSTOM_OPT -no-warn ${src_file} -o \$LLVM_CUSTOM_OUTPUT}
 
 csynth_design
+
+exit
+EOF
+
+  echo "${dst_file}"
+}
+
+# Generate tb_gen.tcl that generates the test bench.
+# Returns the full file path of tb_gen.tcl
+function gen_vitis_tbgen_tcl() {
+  local src_file="${1}"
+  local src_base
+  local src_dir
+  local dst_file
+  local top_func
+  local polybench_dir="${WORKDIR}"
+  local config="config_bind -effort high"
+
+  src_dir="$(dirname "${src_file}")"
+  src_base="$(basename "${src_dir}")"
+  dst_file="$(dirname "${src_file}")/tb_gen.tcl"
+  top_func="$(get_top_func "${src_file}")"
+
+  # Disable high effort in debug mode.
+  if [[ ${DEBUG} -eq 1 ]]; then
+    config=""
+  fi
+
+  # Remove 'static' in all functions - the top design cannot be static
+  sed -i 's/static//g' "${src_dir}/${src_base}.c"
+
+  # Testbench generation script / C baseline
+  # TODO: need to handle these lib and polybench.c properly
+  cat <<EOF > "${dst_file}"
+open_project -reset tb
+add_files {${src_dir}/${src_base}.c} -cflags "-I ${src_dir} -I ${polybench_dir}/utilities -DMINI_DATASET" -csimflags "-I ${src_dir} -I ${polybench_dir}/utilities -DMINI_DATASET"
+add_files -tb {${src_dir}/${src_base}.c ${polybench_dir}/utilities/polybench.c} -cflags "-I ${src_dir} -I ${polybench_dir}/utilities -DMINI_DATASET" -csimflags "-I ${src_dir} -I ${polybench_dir}/utilities -DMINI_DATASET"
+set_top ${top_func}
+
+open_solution -reset solution1
+set_part "zynq"
+create_clock -period "100MHz"
+${config}
+
+csim_design
+csynth_design
+cosim_design
+
+exit
+EOF
+
+  echo "${dst_file}"
+}
+
+# Generate cosim.tcl file that generates the test bench.
+# Returns the full file path of cosim.tcl
+function gen_vitis_cosim_tcl() {
+  local src_file="${1}"
+  local src_base
+  local src_dir
+  local dst_file
+
+  src_dir="$(dirname "${src_file}")"
+  src_base="$(basename "${src_dir}")"
+  dst_file="$(dirname "${src_file}")/cosim.tcl"
+
+  cat <<EOF > "${dst_file}"
+open_project tb
+
+open_solution solution1
+
+cosim_design
+
 exit
 EOF
 
@@ -196,12 +301,54 @@ EOF
 # Run Vitis.
 function run_vitis() {
   local src_file="${1}"
+  local phism_tcl_file
   local src_dir
   
   src_dir="$(dirname "${src_file}")"
+  phism_tcl_file="$(gen_vitis_phism_tcl "${src_file}")"
 
   cd "${src_dir}"
-  vitis_hls "${src_file}" &>/dev/null
+
+  # Synthesize for Phism
+  vitis_hls "${phism_tcl_file}" &> "${src_dir}"/vhls.syn.log
+
+  # Generate test bench
+  if [[ ${ENABLE_COSIM} -eq 1 ]]; then
+    local tbgen_tcl_file
+    local cosim_tcl_file
+
+    tbgen_tcl_file="$(gen_vitis_tbgen_tcl "${src_file}")"
+    cosim_tcl_file="$(gen_vitis_cosim_tcl "${src_file}")"
+
+    vitis_hls "${tbgen_tcl_file}" &> "${src_dir}"/vhls.tbgen.log
+    if grep -q "C/RTL co-simulation finished: FAIL" "${src_dir}"/vhls.tbgen.log; then
+      echo "*** C/RTL co-simulation finished: C BASELINE - FAIL ***"
+    elif ! grep -q "C/RTL co-simulation finished: PASS" "${src_dir}"/vhls.tbgen.log; then
+      echo "*** C/RTL co-simulation failed: C BASELINE - UNKNOWN ERROR ***"
+    fi
+
+    if [ ! -d "${src_dir}"/tb/solution1/sim/verilog/ ]; then
+      echo "tbgen failed to create the target directory: "
+      echo "  ${src_dir}/tb/solution1/sim/verilog/"
+      exit 1
+    fi
+
+    # Copy the kernel from Phism to the test bench
+    cp "${src_dir}"/proj/solution1/syn/verilog/*.v* "${src_dir}"/tb/solution1/sim/verilog/
+    
+    # Run co-simulation
+    vitis_hls "${cosim_tcl_file}" &> "${src_dir}"/vhls.cosim.log
+    if grep -q "C/RTL co-simulation finished: FAIL" "${src_dir}"/vhls.cosim.log; then
+      echo "*** C/RTL co-simulation finished: PHISM - FAIL ***"
+    elif ! grep -q "C/RTL co-simulation finished: PASS" "${src_dir}"/vhls.cosim.log; then
+      echo "*** C/RTL co-simulation failed: PHISM - UNKNOWN ERROR ***"
+    fi
+
+  fi
+
+  # Read time from vitis_hls.log
+  # e.g. $finish called at time : 13920290 ps
+  # JC: there is a formula to convert this to cycles, but I do not remember now - it should be OK for now
 
   local status=$?
 
@@ -220,14 +367,14 @@ function eval_file() {
   local kern_src_file
 
   mlir_src_file="$(compile_c_to_mlir "${src_file}")"
-  kern_src_file="$(extract_top_func_from_mlir "${mlir_src_file}")"
+  prep_src_file="$(preprocess_mlir "${mlir_src_file}")"
+  kern_src_file="$(extract_top_func_from_mlir "${prep_src_file}")"
   poly_src_file="$(polymer_opt "${kern_src_file}")"
   llvm_src_file="$(lower_mlir_to_llvm "${poly_src_file}")"
   vitis_src_file="$(opt_llvm_for_vitis "${llvm_src_file}")"
-  vitis_tcl_file="$(gen_vitis_tcl "${vitis_src_file}")"
 
   local status
-  status="$(run_vitis "${vitis_tcl_file}")"
+  status="$(run_vitis "${vitis_src_file}")"
 
   if [[ "${status}" = "0" ]]; then
     echo " SUCCESS"
@@ -274,7 +421,6 @@ function copy_source_files() {
 # Main entry.
 function main() {
   local polybench_dir="${1}"
-  local tmp_dir="/tmp/phism/pb-flow.${TIMESTAMP}"
 
   # Welcome messages.
   echo ""
@@ -283,11 +429,11 @@ function main() {
   echo "Setup:"
   echo "  TIMESTAMP:     ${TIMESTAMP}"
   echo "  POLYBENCH_DIR: ${polybench_dir}"
-  echo "  WORKING_DIR:   ${tmp_dir}"
+  echo "  WORKING_DIR:   ${WORKDIR}"
   echo ""
 
-  copy_source_files "${polybench_dir}" "${tmp_dir}"
-  eval_dir "${tmp_dir}"
+  copy_source_files "${polybench_dir}" "${WORKDIR}"
+  eval_dir "${WORKDIR}"
 }
 
 # ----------------------- MAIN -------------------------
